version: "1.0"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        NODE_ENV: production
        # NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME}
        NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION}
        # NEXT_PUBLIC_ENCRYPTION_KEY: ${NEXT_PUBLIC_ENCRYPTION_KEY}
        # NEXT_PUBLIC_ENABLE_NOTIFICATIONS: ${NEXT_PUBLIC_ENABLE_NOTIFICATIONS}
        # NEXT_PUBLIC_ENABLE_PAGINATION: ${NEXT_PUBLIC_ENABLE_PAGINATION}
        # NEXT_PUBLIC_ENABLE_GOOGLE_CALENDAR: ${NEXT_PUBLIC_ENABLE_GOOGLE_CALENDAR}
    container_name: RunTaskX-frontend
    environment:
      NODE_ENV: production
      # NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL:-http://localhost:3001/api}
      NEXT_PUBLIC_APP_NAME: ${NEXT_PUBLIC_APP_NAME:-RunTaskX}
      NEXT_PUBLIC_APP_VERSION: ${NEXT_PUBLIC_APP_VERSION:-1.0.0}
      # Security
      NEXTAUTH_SECRET: ${NEXTAUTH_SECRET}
      # NEXT_PUBLIC_ENCRYPTION_KEY: ${NEXT_PUBLIC_ENCRYPTION_KEY}
    ports:
      - "3002:3002"
    depends_on:
      api-server:
        condition: service_healthy
    networks:
      - run-task-x-network
    healthcheck:
      test:
        [
          "CMD",
          "wget",
          "--no-verbose",
          "--tries=1",
          "--spider",
          "http://localhost:3002",
        ]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local

networks:
  ita-sys-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16
